### ISSUE TITLE
decide on mark-as-watched behavior 

### ISSUE THREAD

**Issue by lortza** [lortza/moviedb#16]
- [x] new to watch / seen boolean
 - [x] add new to watch / seen boolean to Movie table
 - [x] add boolean button to movie tile on home page
 - [x] add boolean button to show page
- [x] redeploy to heroku

**Comment by mikevallano** [comment]
For this and the homepage one, using javascript and ajax would make sense, and it'd be a good example for you to learn. Just let me know if you want help or input or if you want me to do it and then show you.
