### ISSUE TITLE
Incorporate trailers somehow

### ISSUE THREAD

**Issue by mikevallano** [lortza/moviedb#34]
At minimum, do a youtube search for "[title] movie trailer".
 * Button to youtube search url (https://www.youtube.com/results?search_query=#{movie.title}+movie+trailer)
 * Append with "official trailer"
 * Open in a separate tab

It'd be real sweet to scrape and embed the first result off of youtube for that search.

**Comment by lortza** [comment]
that would be awesome! right now the trailer field is called `preview_link` and we have to enter it manually. so scraping and embedding would be a big upgrade. i think we should search for "[title] official trailer."

**Comment by lortza** [comment]
there were some weird issues with the button_to not actually loading the full search url (even though it was rendering in chrome dev tools) so i did it via an href.
