### ISSUE TITLE
Handle titles that don't match API

### ISSUE THREAD

**Issue by lortza** [lortza/moviedb#4]
- [x] get API info
 - [x] secrets, etc
- [x] get sample hash
- [x] create methods to employ API??

- [x] Make sure we're handling movie submissions properly to account for incorrect movie titles, misspellings, etc., or sometimes we may not want to use the API?
- [ ] notification: API title not found
- [ ] decide how to handle entry form and all of the overwhelming fields we may not need

**Comment by mikevallano** [comment]
The connection is working so that if you enter a title, it retrieves data from the API and adds that in the create method. We need to decide:

What should we pull from the API
What fields should we remove from the form field (since they'll be populated by the API)

For reference, here's an example of what the API provides: http://www.omdbapi.com/?t=fargo&y=&plot=short&r=json

**Comment by lortza** [comment]
FYI i donated to the API to get movie posters

**Comment by lortza** [comment]
here's the sample output: http://www.omdbapi.com/?t=fargo&y=&plot=short&r=json

"Title": "Fargo",
    "Year": "1996",
    "Rated": "R",
    "Released": "5 Apr 1996",
    "Runtime": "98 min",
    "Genre": "Crime, Drama, Thriller",
    "Director": "Joel Coen, Ethan Coen",
    "Writer": "Ethan Coen, Joel Coen",
    "Actors": "William H. Macy, Steve Buscemi, Peter Stormare, Kristin Rudrüd",
    "Plot": "Jerry Lundegaard's inept crime falls apart due to his and his henchmen's bungling and the persistent police work of the quite pregnant Marge Gunderson.",
    "Language": "English",
    "Country": "USA, UK",
    "Awards": "Won 2 Oscars. Another 77 wins & 42 nominations.",
    "Poster": "http://ia.media-imdb.com/images/M/MV5BMTgxNzY3MzUxOV5BMl5BanBnXkFtZTcwMDA0NjMyNA@@._V1_SX300.jpg",
    "Metascore": "85",
    "imdbRating": "8.2",
    "imdbVotes": "389742",
    "imdbID": "tt0116282",
    "Type": "movie",
    "Response": "True"
